[2025-02-27T16:45:45.046+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T16:45:45.051+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T16:31:28.224839+00:00 [queued]>
[2025-02-27T16:45:45.053+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T16:31:28.224839+00:00 [queued]>
[2025-02-27T16:45:45.053+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 5
[2025-02-27T16:45:45.057+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): fetch_data_from_url> on 2025-02-27 16:31:28.224839+00:00
[2025-02-27T16:45:45.059+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=748) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-27T16:45:45.060+0000] {standard_task_runner.py:72} INFO - Started process 750 to run task
[2025-02-27T16:45:45.060+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'send_to_snowflake', 'fetch_data_from_url', 'manual__2025-02-27T16:31:28.224839+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/send_to_snowflakes.py', '--cfg-path', '/tmp/tmp65owop1u']
[2025-02-27T16:45:45.061+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask fetch_data_from_url
[2025-02-27T16:45:45.076+0000] {task_command.py:467} INFO - Running <TaskInstance: send_to_snowflake.fetch_data_from_url manual__2025-02-27T16:31:28.224839+00:00 [running]> on host b80dd83948db
[2025-02-27T16:45:45.104+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_to_snowflake' AIRFLOW_CTX_TASK_ID='fetch_data_from_url' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T16:31:28.224839+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T16:31:28.224839+00:00'
[2025-02-27T16:45:45.104+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-27T16:45:45.397+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-27T16:45:45.400+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-27T16:45:45.400+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=send_to_snowflake, task_id=fetch_data_from_url, run_id=manual__2025-02-27T16:31:28.224839+00:00, execution_date=20250227T163128, start_date=20250227T164545, end_date=20250227T164545
[2025-02-27T16:45:45.411+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-02-27T16:45:45.419+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T16:45:45.419+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
